### ISSUE TITLE
lack of good documentation, usage are not good

### ISSUE THREAD

**Issue by mckaygerhard** [Mobius1/Selectr#2]
i try u'r good library, but the lack of CLEAR documentation make many users lack of usage it!

when i try the pickathing flavor for the select with search combobox i got a easy to implement javascript select input box, that works at firts try.. 

with u'r documentation (that not explain where to put or how the js code) i need to try many times until got with some good results

1) not clear about how:
```
... and include the JS file near the bottom of your document's body
<script type="text/javascript" src="/path/to/selectr.min.js"></script>
```
what exaclty means "near", its vage and ambigous, and hard to do if it use a frameworks (that many put many code at the "near" of the end body tag)

2) complety miscunderstand about initialization:
```
var mySelect = document.querySelector('select');
var mySelectr = new Selectr(mySelect);
```
the piece of code generates two errors (depending):
2.1 * selectr.min.js:107 Uncaught TypeError: this.elem.getBoundingClientRect is not a function
this is at Plugin (selectr.min.js:107)
2.2 *  seletr need and element id to work
this is when using exactly the documentation suggested, due the right way its `document.getelementById` in novice cases, althrought i dont nkow if its the right way 

i posted and iisue about the last

i can help with good documentation but i need more eplaint and comments in the code, due in'm not expert

**Comment by Mobius1** [comment]
The plugin is currently being rebuilt and full documentation is being [worked on](http://mobius.ovh/docs/selectr). If you check the notice on the main page it indicates that I wrote Selectr for my own project and that I intend on rewriting it for everyone to use.

>what exaclty means "near", its vage and ambigous, and hard to do if it use a frameworks (that many put many code at the "near" of the end body tag)

I apologise if it was ambiguous, but adding javascript at the end of the body is a common method that allows the page to potentially render faster as all the painting can be done before the javascript it parsed rather than the other way around.

> complety miscunderstand about initialization:
That's actually a bad example I used and I'm sorry for any misunderstanding. I assume developers would understand, but I've updated the documentation so it's a little less vague.

**Comment by mckaygerhard** [comment]
if i' could help with more let me know, i'll wait for the next release for close this issue

**Comment by mckaygerhard** [comment]
NOTE: i hate too the stupid jquery and i lke the easy to use - non complicated things..

but as u can note, we created complicated things to use as easy things.. (u'r js code:complicate, usage : simple, ironic no?)

the note at the end of the README are too hard i thing, its a good javacript library that helps people like me

**Comment by mckaygerhard** [comment]
WOW! great! some examples does not have the "with xxx enabled" counterpart but dont worry its ok and looks pretty good!

great job!
